#!/bin/bash

declare -a algs=('weka.J48' 'weka.NaiveBayes' 'weka.JRip' 'weka.IBk' 'weka.PART' 'weka.Logistic')
declare -a metaLearners=('randomForest_RandomFeatures' 'cforest_RandomFeatures' 'randomForest_AllFeatures' 'cforest_AllFeatures')


if [ "$1" = "regression" ]
then
    echo $1
	parallel Rscript meta-learning_regression_allTrans.R {} ::: ${algs[*]} ::: ${metaLearners[*]}#run the .R file in parallel with the arguments given by the array
elif [ "$1" = "classification" ]
then
	echo $1
	parallel Rscript meta-learning_classification_allTrans.R {} ::: ${algs[*]} ::: ${metaLearners[*]} #run the .R file in parallel with the arguments given by the array
else
	echo "Please type either [regression] or [classification] as input parameter"
fi

#Rscript meta-learning.R ${algs[0]}
